version: "3"

services:
  linux-build:
    image: project-faster/qpep_linux
    build:
      context: .
    environment:
      - QPEP_REPO=https://github.com/Project-Faster/qpep.git
      - QPEP_BRANCH=issue-22-performance-testing
      - QPEP_REV=HEAD
    volumes:
      - ./build:/build
