
acks: 10
ackdelay: 25
backend: quic-go
ccalgorithm: reno
ccslowstart: search
certificate: server_cert.pem
certificate_key:
decimate: 4
decimatetime: 100
maxretries: 10
gateway: 198.18.0.254
port: 443
apiport: 444
listenaddress: 0.0.0.0
listenport: 9443
multistream: true
verbose: false
preferproxy: false
varackdelay: 0
threads: 4
