#!/usr/bin/env bash

rm -f /tmp/qpep-postinstall.log
touch /tmp/qpep-postinstall.log

{
echo "[QPep post-install script]"
date

echo ">> Fix permissions"
chown -R $USER:staff /Applications/QPep.app
chmod -R 0755 /Applications/QPep.app

echo """#!/bin/bash
osascript -e 'Tell application \"System Events\" to display dialog \"Password:\" default answer \"\" with hidden answer' -e 'text returned of result'
""" > /Applications/QPep.app/Contents/MacOS/askpass.sh

chmod 0755 /Applications/QPep.app/Contents/MacOS/askpass.sh
chmod +x /Applications/QPep.app/Contents/MacOS/askpass.sh

mkdir /Applications/QPep.app/Contents/MacOS/log
chown -R $USER:staff /Applications/QPep.app/Contents/MacOS/log
chmod -R 0755 /Applications/QPep.app/Contents/MacOS/log

if [[ -d /tmp/qpep-config ]]; then
  echo ">> Restoring previous configuration"
  rm -rf /Applications/QPep.app/Contents/MacOS/config
  mv /tmp/qpep-config /Applications/QPep.app/Contents/MacOS/config
fi

echo ">> Remove previous service if present"
export SUDO_ASKPASS=/Applications/QPep.app/Contents/MacOS/askpass.sh

sudo -S -E -u "$USER" /bin/bash -c 'cd /Applications/QPep.app/Contents/MacOS/ && ./qpep --client --service uninstall' || true

echo ">> Install client service"
sudo -S -E -u "$USER" /bin/bash -c 'cd /Applications/QPep.app/Contents/MacOS/ && ./qpep --client --service install' || true

ls /Users/$USER/Library/LaunchAgents/

echo ">> Fix service permission"
sudo -S chown root:wheel "/Users/$USER/Library/LaunchAgents/qpep-client.plist"
sudo -S chmod o-w "/Users/$USER/Library/LaunchAgents/qpep-client.plist"

#echo ">> Start application..."
#open -n -a /Applications/QPep.app

echo "Done"
}  &> /tmp/qpep-postinstall.log

exit 0
