# Performance server

# set environment variables before running:
# SERVER_PUBLIC_ADDRESS

version: "1.0"
services:
  collector:
    user: root
    environment:
      - ELASTIC_CONTAINER=false
    build:
      context: ./logstash
      dockerfile: Dockerfile
    depends_on:
      queue:
        condition: service_started
    extra_hosts:
      - "MQTT:${SERVER_PUBLIC_ADDRESS}"
      - "LOGSTASH:${SERVER_PUBLIC_ADDRESS}"
    ports:
      - target: 5044
        published: 5044
        protocol: tcp
        mode: host
    network_mode: "host"
    volumes:
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/mqtt.conf:/usr/share/logstash/pipeline/mqtt.conf
      - ./output/:/usr/share/logstash/output

  queue:
    image: "project-faster/mosquitto"
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    depends_on:
      server:
        condition: service_started
    extra_hosts:
      - "MQTT:${SERVER_PUBLIC_ADDRESS}"
      - "LOGSTASH:${SERVER_PUBLIC_ADDRESS}"
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
    network_mode: "host"
    volumes:
      - ./mosquitto/mosquitto.conf:/etc/mosquitto/mosquitto.conf

  server:
    image: "project-faster/qpep_server"
    extra_hosts:
      - "MQTT:${SERVER_PUBLIC_ADDRESS}"
      - "QPEP_GATEWAY:${SERVER_PUBLIC_ADDRESS}"
      - "QPEP_ADDRESS:${LISTEN_ADDRESS}"
    ports:
      - target: 1443
        published: 1443
        protocol: udp
        mode: host
    network_mode: "host"
    volumes:
      - ./server:/build/config
    entrypoint:
      - /root/run-qpep.sh
