# Performance server

# set environment variables before running:
# QPEP_BACKEND
# QPEP_CCA
# GO_VERSION
# QPEP_REPO
# QPEP_BRANCH
# QPEP_REV
# QPEP_ADDRESS
# QPEP_GATEWAY

version: "1.0"
volumes:
  outputdata:
services:
  server:
    image: "project-faster/qpep-server"
    build:
      context: server/
      args:
        - GO_VERSION
        - QPEP_REPO
        - QPEP_BRANCH
        - QPEP_REV
        - QPEP_BACKEND
        - QPEP_CCA
        - QPEP_SLOWSTART
        - QPEP_ADDRESS
        - QPEP_GATEWAY
    ports:
      - target: 1443
        published: 1443
        protocol: udp
        mode: host
    network_mode: "host"
    extra_hosts:
      - "MQTT:${SERVER_ADDRESS}"
    volumes:
      - outputdata:/root
    entrypoint:
      - /root/run-qpep.sh
      - ${QPEP_REPO}
      - ${QPEP_BRANCH}
      - ${QPEP_REV}
      - ${QPEP_CCA}
      - ${QPEP_ADDRESS}
      - ${QPEP_BACKEND}
      - ${QPEP_SLOWSTART}
