# Performance server

# set environment variables before running:
# SERVER_ADDRESS

version: "1.0"
services:
  server:
    image: "project-faster/qpep_server"
    extra_hosts:
      - "MQTT:${SERVER_ADDRESS}"
      - "QPEP_GATEWAY:127.0.0.1"
      - "QPEP_ADDRESS:${SERVER_ADDRESS}"
    environment:
      - "QPEP_BRANCH=issue-22-performance-testing"
      - "QPEP_REPO=https://github.com/parvit/qpep.git"
      - "QPEP_BACKEND:${SERVER_BACKEND}"
      - "QPEP_CCA:${SERVER_CCA}"
    ports:
      - target: 1443
        published: 1443
        protocol: udp
        mode: host
    network_mode: "host"
    volumes:
      - ./server:/build
    entrypoint:
      - /root/run-qpep.sh
