# Performance server

# set environment variables before running:
# SERVER_ADDRESS

version: "1.0"
services:
  server:
    image: "project-faster/qpep-server"
    extra_hosts:
      - "MQTT:${SERVER_ADDRESS}"
      - "QPEP_GATEWAY:127.0.0.1"
      - "QPEP_ADDRESS:${SERVER_ADDRESS}"
    ports:
      - target: 1443
        published: 1443
        protocol: udp
        mode: host
    network_mode: "host"
    entrypoint:
      - /root/run-qpep.sh
