name: Go

on:
  push:
    branches: [ "main", "issue-10" ]
  pull_request:
    branches: [ "main" ]

jobs:

#  build-linux:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up Go
#      uses: actions/setup-go@v3
#      with:
#        go-version: 1.16
#    - name: Build
#      run: go build -v ./...
#    - name: Test
#      run: go test -v ./...

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16
    - name: Build
      run: go build -v
    - name: Test
      run: go test -v ./...
