name: BuildAll

on:
  workflow_dispatch:
  push:
    branches: [ "main", "testing", "issue-10" ]
  pull_request:
    branches: [ "main" ]

jobs:

#  build-linux:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up Go
#      uses: actions/setup-go@v3
#      with:
#        go-version: 1.16
#    - name: Build
#      run: go build -v ./...
#    - name: Test
#      run: go test -v ./...

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16
        
    - name: Test
      run: go test -v ./...
      continue-on-error: true
      
    - uses: actions/checkout@v2
    - name: Install Wix
      uses: actions/checkout@v2
      with:
        repository: fbarresi/wix
        path: wix

    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Prepare
      run: |
           MKDIR build
           MKDIR build\x64
           MKDIR build\x86
           COPY /Y windivert\LICENSE build\LICENSE.windivert
           COPY /Y LICENSE build\LICENSE
           set GOARCH=amd64
           go clean -cache
           set GOARCH=386
           go clean -cache
           COPY /Y windivert\x64\* build\x64
      shell: cmd
           
    - name: Build QPep x64
      run: |
           set GOARCH=amd64
           set CGO_ENABLED=1
           go build -o build\x64\qpep.exe
      shell: cmd
           
    - name: Build QPep Tray x64
      run: |
           pushd qpep-tray
           set GOARCH=amd64
           set CGO_ENABLED=0
           go build -ldflags -H=windowsgui -o ..\build\x86\qpep-tray.exe
           popd
      shell: cmd
           
    - name: Build QPep x86
      run: |
           set GOARCH=386
           set CGO_ENABLED=1
           go build -o build\x64\qpep.exe
      shell: cmd
           
    - name: Build QPep Tray x86
      run: |
           pushd qpep-tray
           set GOARCH=386
           set CGO_ENABLED=0
           go build -ldflags -H=windowsgui -o ..\build\x86\qpep-tray.exe
           popd
      shell: cmd
      
    - name: Build QPep Installer
      run: |
           set PATH=${{ github.workspace }}\wix\tools;%PATH%
           msbuild installer\installer.sln
      shell: cmd
   
    - uses: actions/upload-artifact@v3
      with:
        name: QPep-${{ github.job }}-${{ github.run_id }}
        path: build\installer.msi
