name: PerformanceTests

on:
  schedule:
    - cron: '1 1 * * *'

run-name: Performance Testing [${{ github.event_name }}][${{ github.head_ref || github.ref_name }}] - ${{ inputs.server_public_address || '35.163.142.7' }}/${{ inputs.connect_delay_ms || '500' }}ms delay

jobs:
  test-matrix:
    strategy:
      matrix:
        download_size: [ 10 ]
        connection_delay: [ 0, 500 ]
        connections_number: [ 1, 4 ]
        backend: [ 'quic-go', 'quicly-go' ]
        cca: [ 'reno', 'search' ]
        exclude:
          - backend: 'quic-go'
            cca: 'search'
    uses: 'common-perfomance.yml'
        with:
      download_size: ${{ matrix.download_size }}
      connections_number: ${{ matrix.connections_number }}
      backend: ${{ matrix.backend }}
      cca: ${{ matrix.cca }}
      connection_delay_ms: ${{ matrix.connection_delay }}
    secrets: inherit
