name: PerformanceTests

run-name: Performance Testing

on:
  workflow_dispatch:
    gateway_address:
      description: 'address for client to use as gateway'
      type: string
      default: 35.163.142.7
      required: true

jobs:
  run-client:
    runs-on: vm-client
    steps:
      - name: Build
        run: |
          echo Check Client!
          docker version
          sleep 2

  run-server:
    runs-on: vm-server
    steps:
      - name: Build
        run: |
          echo Check Server!
          docker version
          sleep 2

  check:
    needs: [ run-client, run-server ]
    runs-on: vm-server
    steps:
      - name: Final Check
        run: |
          echo Check Results!
          sleep 2
