name: PerformanceTests

run-name: Performance Testing

on:
  workflow_dispatch:
    gateway_address:
      description: 'address for client to use as gateway'
      type: string
      default: 192.168.1.50
      required: true

jobs:
  run-client:
    runs-on: vm-client
    env:
      LISTEN_ADDRESS: 127.0.0.1
      REMOTE_GATEWAY: ${{ github.inputs.gateway_address }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Prepare
        run: |
          mkdir config/
          echo sed -E 's/%QPEP_GATEWAY%/$REMOTE_GATEWAY"/'  -E 's/%QPEP_ADDRESS%/LISTEN_ADDRESS"/' docker/client-env/qpep.yml.tpl > config/qpep.yml
          sed -E 's/%QPEP_GATEWAY%/$REMOTE_GATEWAY"/'  -E 's/%QPEP_ADDRESS%/LISTEN_ADDRESS"/' docker/client-env/qpep.yml.tpl > config/qpep.yml

      - name: Build Client
        run: |
          go build -v -o qpep.exe

      - name: Run Client
        run: |
          setsid ./qpep.exe &> /dev/null
          sleep 10

      - name: Cleanup
        if: always()
        run: |
          kill -s 9 $(pidof -s qpep.exe)
          rm -rf ${{ github.workspace }}/*

  run-server:
    runs-on: vm-server
    env:
      CONTAINERS_SUBNET: 192.168.1.0/24
      MQTT_ADDRESS: 192.168.1.51
      LOGSTASH_ADDRESS: 192.168.1.52
      LISTEN_ADDRESS: 127.0.0.1
      REMOTE_GATEWAY: ${{ github.inputs.gateway_address }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build Server
        run: |
          echo Check Server!
          ls
          docker version
          cd docker/
          pushd build-linux/
          docker build -t project-faster/qpep_server .
          popd
          pushd performance-env/
          docker compose up -d
          popd
          sleep 2

      - name: Cleanup
        if: always()
        run: |
          cd docker/build-linux/
          docker compose down -v
          cd ../../
          rm -rf ${{ github.workspace }}/*

  check:
    needs: [ run-client, run-server ]
    runs-on: vm-server
    steps:
      - name: Final Check
        run: |
          echo Check Results!
          sleep 2
