name: PerformanceTests

on:
  workflow_dispatch:
    inputs:
      gateway_address:
        description: 'address for client to use as gateway'
        type: string
        default: 192.168.1.50
        required: true

run-name: Performance Testing - ${{ inputs.gateway_address }}

jobs:
  run-client:
    runs-on: vm-client
    env:
      LISTEN_ADDRESS: 127.0.0.1
      REMOTE_GATEWAY: ${{ inputs.gateway_address }}
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v3

#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.18.10
#
      - name: Prepare
        shell: powershell
        run: |
          New-Item -Path . -Name "config" -ItemType "directory" -Force
          New-Item -Path . -Name "build" -ItemType "directory" -Force
          (Get-Content -Path ./docker/client-env/qpep.yml.tpl) -match '%QPEP_GATEWAY%' -replace '$REMOTE_GATEWAY' > config/qpep.yml
          (Get-Content -Path ./config/qpep.yml) -match '%QPEP_ADDRESS%' -replace '$LISTEN_ADDRESS' > config/qpep.yml
          Get-Content -Path ./config/qpep.yml

      - name: Build Client
        shell: cmd
        run: |
          set CGO_ENABLED=1
          set GOOS=windows
          set GOHOSTARCH=amd64
          set GOHOSTOS=windows
          go build -v -o build/qpep.exe

      - name: Run Client
        shell: powershell
        run: |
          Copy-Item "./windivert/x64/*" -Destination "./build"
          Start-Process "./build/qpep.exe" -WorkingDir "./build"

      - name: Run Tests
        shell: powershell
        run: |
          sleep 10

      - name: Stop Client
        if: always()
        shell: powershell
        run: |
          Get-Process qpep | Stop-Process

      - uses: rtCamp/action-cleanup@master

#  run-server:
#    runs-on: vm-server
#    env:
#      CONTAINERS_SUBNET: 192.168.1.0/24
#      MQTT_ADDRESS: 192.168.1.51
#      LOGSTASH_ADDRESS: 192.168.1.52
#      LISTEN_ADDRESS: 127.0.0.1
#      REMOTE_GATEWAY: ${{ github.inputs.gateway_address }}
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.18
#
#      - name: Build Server
#        run: |
#          echo Check Server!
#          ls
#          docker version
#          cd docker/
#          pushd build-linux/
#          docker build -t project-faster/qpep_server .
#          popd
#          pushd server-env/
#          docker compose up -d
#          popd
#          sleep 2
#
#      - name: Cleanup
#        if: always()
#        run: |
#          cd docker/build-linux/
#          docker compose down -v
#          cd ../../
#
#      - uses: rtCamp/action-cleanup@master
#
#  check:
#    needs: [ run-client, run-server ]
#    runs-on: vm-server
#    steps:
#      - name: Final Check
#        run: |
#          echo Check Results!
#          sleep 2
